#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


echo -e "-Create Mesh"
./Allmesh

echo -e "- Copy 0.orig to 0"
cp -r 0.orig 0

echo -e "- Decompose case"
decomposePar

mpirun -np 12 pimpleFoam -parallel >> logSimulation
 
reconstructPar


#sudo apt update && sudo apt upgrade -y
#sudo apt install -y mesa-utils libgl1-mesa-dri libxcb-xinerama0 libxcb-icccm4
#
#------------------------------------------------------------------------------
